// Checked source transformation (mandate B2): scopes the two frozen V197
// sheets to their stage body-classes. Entry rules activate only under
// body.front-v61-active; universe rules only under body.universe-edition.
// @keyframes/@font-face internals are never prefixed. :root/body map onto the
// stage class so tokens live per-stage. No selector is renamed or dropped.
import fs from "node:fs";
import postcss from "postcss";
import prefixer from "postcss-prefix-selector";

const jobs = [
  ["src/styles/v197-entry.css", "src/styles/v197-entry-scoped.css", "body.front-v61-active"],
  ["src/styles/v197-universe.css", "src/styles/v197-universe-scoped.css", "body.universe-edition"],
];
for (const [src, out, scope] of jobs) {
  const css = fs.readFileSync(src, "utf8");
  const res = postcss([
    prefixer({
      prefix: scope,
      transform(prefix, selector, prefixed) {
        const s = selector.trim();
        if (s === "html") return prefix;                    // html-level paints belong to the stage
        if (s === ":root" || s === "body") return prefix;   // tokens/body rules live on the stage class
        if (s.startsWith("html ")) return prefix + s.slice(4);
        if (s.startsWith("body.front-v61-active") || s.startsWith("body.universe-edition") ||
            s.startsWith("body.nur-universe-active")) return s; // already stage-scoped in source
        if (s.startsWith("body")) return prefix + s.slice(4);
        return prefixed;                                    // default: "scope selector"
      },
    }),
  ]).process(css, { from: src });
  fs.writeFileSync(out, `/* GENERATED by scripts/scope-v197.mjs — do not edit; edit the raw sheet. */\n` + res.css);
  console.log(out, res.css.length, "bytes");
}
